# Generated by Django 5.1.6 on 2025-02-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='borrowed_books', to='App.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='readers', to='App.book'),
        ),
    ]
