# Generated by Django 5.1.6 on 2025-03-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_book_users_user_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISBN',
            new_name='isbn',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
