# Generated by Django 5.1.6 on 2025-02-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_added_book_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='added_by',
            new_name='borrow_by',
        ),
    ]
