# Generated by Django 5.1.6 on 2025-03-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_billing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='price_perDay',
        ),
        migrations.AddField(
            model_name='book',
            name='price_perDay',
            field=models.FloatField(default=3.0),
            preserve_default=False,
        ),
    ]
