# Generated by Django 5.1.6 on 2025-02-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_author_book_author_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category_of_book',
            new_name='category_of_book_You_want_to_borrow',
        ),
    ]
