# Generated by Django 5.1.6 on 2025-02-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_category_of_book_book_category_of_book_you_want_to_borrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category_of_book_You_want_to_borrow',
            new_name='book_catogery',
        ),
    ]
