# Generated by Django 5.1.6 on 2025-03-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_book_borrow_by_alter_book_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_by', to='App.user'),
            preserve_default=False,
        ),
    ]
