# Generated by Django 5.1.6 on 2025-02-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_rename_category_of_book_you_want_to_borrow_book_book_catogery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_catogery',
            new_name='book_catogory',
        ),
    ]
