# Generated by Django 5.1.6 on 2025-02-24 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_rename_book_catogery_book_book_catogory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_number',
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default=0, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='copies',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrow_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.user'),
        ),
    ]
