# Generated by Django 5.1.6 on 2025-02-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_book_book_number_book_isbn_book_copies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrow_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='App.user'),
        ),
    ]
