# Generated by Django 5.1.6 on 2025-02-24 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_rename_copies_book_copies_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='copies_no',
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrow_by',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='App.user'),
            preserve_default=False,
        ),
    ]
