# Generated by Django 5.1.6 on 2025-02-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_remove_book_is_borrowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='copies',
        ),
        migrations.AddField(
            model_name='book',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
