# Generated by Django 5.1.6 on 2025-02-26 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_booktransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_borrowed',
            new_name='want_to_borrow',
        ),
    ]
