# Generated by Django 5.1.6 on 2025-02-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_rename_want_to_borrow_book_is_borrowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='avaliable_copies_in_inventory',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='total_copies',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
